apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    access: proxy
    basicAuth: false
    id: 1
    isDefault: true
    jsonData: {}
    orgId: 1
    readOnly: false
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    url: http://prometheus.service.sentella.systems:9090